package com.example.ui.theme

object Localization {
    private val translations = mapOf(
        "en" to mapOf(
            "app_title" to "OmniChat AI",
            "chat" to "Chat",
            "providers" to "AI Providers",
            "memory" to "Memory",
            "mcp" to "MCP Tools",
            "settings" to "Settings",
            "new_chat" to "New Chat",
            "no_chats" to "No conversations yet. Start a new one!",
            "send_hint" to "Ask anything, attach files or images...",
            "active_provider" to "Active Provider",
            "web_search" to "Web Search",
            "recording" to "Listening...",
            "voice_input" to "Voice Input",
            "video_analyze" to "Extracting frames and analyzing video...",
            "autoplay_tts" to "Autoplay Speech (TTS)",
            "system_prompt" to "System Prompt / Instructions",
            "memory_desc" to "Long-term memories stored about you by the AI to maintain context across chats.",
            "add_memory" to "Add New Memory",
            "category" to "Category",
            "content" to "Content",
            "save" to "Save",
            "delete" to "Delete",
            "mcp_desc" to "Model Context Protocol allows models to discover and execute client-side tools dynamically.",
            "add_mcp_server" to "Add MCP Server",
            "server_name" to "Server Name",
            "endpoint_url" to "Endpoint URL",
            "tools_browsing" to "Tools Browser",
            "tts_settings" to "Text-To-Speech Settings",
            "tts_type_local" to "System Native TTS",
            "tts_type_openai" to "Custom OpenAI TTS Endpoint",
            "language" to "Application Language",
            "edit" to "Edit",
            "cancel" to "Cancel",
            "add_provider" to "Add Provider",
            "provider_name" to "Provider Name",
            "base_url" to "API Base URL",
            "api_key" to "API Key / Token",
            "model_name" to "Model Identifier",
            "priority" to "Fallback Priority",
            "enabled" to "Enabled",
            "fallback_indicator" to "Self-Healing Fallback: Active",
            "status_thinking" to "Thinking...",
            "status_searching" to "Searching live web...",
            "status_generating" to "Generating response...",
            "status_summarizing" to "Summarizing conversation...",
            "file_attached" to "File attached",
            "image_attached" to "Image attached",
            "video_attached" to "Video attached",
            "autoplay_title" to "TTS Autoplay",
            "autoplay_on" to "Speech Autoplay is Active",
            "observe_media_title" to "Auto-Analyze New Gallery/Folder Media",
            "observe_media_desc" to "Monitor your gallery and a specified folder. When a new picture/video is added, OmniChat automatically triggers an AI request.",
            "observe_folder_label" to "Custom folder path to observe",
            "observe_prompt_label" to "Auto-trigger prompt template",
            "observe_media_folder_placeholder" to "e.g. /storage/emulated/0/Download",
            "search_chat" to "Search chats...",
            "clear_history" to "Clear Chat History",
            "clear_history_confirm" to "Are you sure you want to delete all conversations? This action cannot be undone.",
            "export_chat" to "Export Chat",
            "export_json" to "Export as JSON",
            "export_markdown" to "Export as Markdown",
            "export_filename_prefix" to "chat_export",
            "time_now" to "Just now",
            "time_minutes" to "%d min ago",
            "time_hours" to "%d h ago",
            "time_days" to "%d d ago",
            "personas_title" to "AI Personas",
            "persona_default" to "General Assistant",
            "persona_coder" to "Expert Coder",
            "persona_writer" to "Creative Writer",
            "persona_researcher" to "Scientific Researcher",
            "persona_tutor" to "Personal Tutor",
            "persona_desc_default" to "Helpful and concise general assistant.",
            "persona_desc_coder" to "Specializes in software development, debugging, and architecture.",
            "persona_desc_writer" to "Creative storyteller, editor, and content creator.",
            "persona_desc_researcher" to "Analyzes data, summarizes papers, and explains complex concepts.",
            "persona_desc_tutor" to "Explains topics simply and helps with learning and education.",
            "wp_settings_title" to "WordPress Integration",
            "wp_url_label" to "Site URL (https://...)",
            "wp_user_label" to "Username",
            "wp_app_pass_label" to "Application Password",
            "wp_auto_post_label" to "Auto-post on Export",
            "wp_post_success" to "Posted to WordPress!",
            "wp_post_error" to "WordPress Post Failed",
            "theme_title" to "App Theme",
            "theme_light" to "Light Mode ☀️",
            "theme_dark" to "Dark Mode 🌙",
            "auto_notify_title" to "Statusbar Notifications",
            "auto_notify_desc" to "Auto-post full request & AI response with Markdown, Math formulas, and Images directly to status bar.",
            "send_test_notification" to "Send Test Notification 🔔"
        ),
        "de" to mapOf(
            "app_title" to "OmniChat AI",
            "chat" to "Chat",
            "providers" to "KI-Anbieter",
            "memory" to "Gedächtnis",
            "mcp" to "MCP Tools",
            "settings" to "Einstellungen",
            "new_chat" to "Neuer Chat",
            "no_chats" to "Noch keine Gespräche. Starten Sie eines!",
            "send_hint" to "Fragen Sie etwas, hängen Sie Dateien oder Bilder an...",
            "active_provider" to "Aktiver Anbieter",
            "web_search" to "Websuche",
            "recording" to "Zuhören...",
            "voice_input" to "Spracheingabe",
            "video_analyze" to "Extrahiere Bilder und analysiere Video...",
            "autoplay_tts" to "Sprachausgabe automatisch abspielen (TTS)",
            "system_prompt" to "System-Prompt / Anweisungen",
            "memory_desc" to "Langzeitgedächtnis, das von der KI über Sie gespeichert wird, um den Kontext chatübergreifend zu wahren.",
            "add_memory" to "Neues Gedächtnis hinzufügen",
            "category" to "Kategorie",
            "content" to "Inhalt",
            "save" to "Speichern",
            "delete" to "Löschen",
            "mcp_desc" to "Model Context Protocol ermöglicht es Modellen, clientseitige Tools dynamisch zu erkennen und auszuführen.",
            "add_mcp_server" to "MCP-Server hinzufügen",
            "server_name" to "Servername",
            "endpoint_url" to "Endpunkt-URL",
            "tools_browsing" to "Tools-Browser",
            "tts_settings" to "Text-to-Speech Einstellungen",
            "tts_type_local" to "Systemeigenes TTS",
            "tts_type_openai" to "Eigener OpenAI TTS Endpunkt",
            "language" to "Anwendungssprache",
            "edit" to "Bearbeiten",
            "cancel" to "Abbrechen",
            "add_provider" to "Anbieter hinzufügen",
            "provider_name" to "Anbietername",
            "base_url" to "API-Basis-URL",
            "api_key" to "API-Schlüssel / Token",
            "model_name" to "Modell-Bezeichner",
            "priority" to "Ausfallpriorität",
            "enabled" to "Aktiviert",
            "fallback_indicator" to "Selbstheilender Fallback: Aktiv",
            "status_thinking" to "Denken...",
            "status_searching" to "Websuche aktiv...",
            "status_generating" to "Antwort wird generiert...",
            "status_summarizing" to "Konversation wird zusammengefasst...",
            "file_attached" to "Datei angehängt",
            "image_attached" to "Bild angehängt",
            "video_attached" to "Video angehängt",
            "autoplay_title" to "TTS Auto-Wiedergabe",
            "autoplay_on" to "Sprachwiedergabe ist aktiv",
            "observe_media_title" to "Neue Medien automatisch analysieren",
            "observe_media_desc" to "Überwacht Ihre Galerie und einen bestimmten Ordner. Wenn ein neues Bild/Video hinzugefügt wird, startet OmniChat automatisch eine KI-Anfrage.",
            "observe_folder_label" to "Zu überwachender benutzerdefinierter Ordnerpfad",
            "observe_prompt_label" to "Vorlage für automatischen Prompt",
            "observe_media_folder_placeholder" to "z.B. /storage/emulated/0/Download",
            "search_chat" to "Chats suchen...",
            "clear_history" to "Chatverlauf löschen",
            "clear_history_confirm" to "Sind Sie sicher, dass Sie alle Gespräche löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.",
            "export_chat" to "Chat exportieren",
            "export_json" to "Als JSON exportieren",
            "export_markdown" to "Als Markdown exportieren",
            "export_filename_prefix" to "chat_export",
            "time_now" to "Gerade eben",
            "time_minutes" to "vor %d Min.",
            "time_hours" to "vor %d Std.",
            "time_days" to "vor %d Tg.",
            "personas_title" to "KI-Personas",
            "persona_default" to "Allgemeiner Assistent",
            "persona_coder" to "Experte für Programmierung",
            "persona_writer" to "Kreativer Schreiber",
            "persona_researcher" to "Wissenschaftlicher Forscher",
            "persona_tutor" to "Privatlehrer",
            "persona_desc_default" to "Hilfreicher und prägnanter allgemeiner Assistent.",
            "persona_desc_coder" to "Spezialisiert auf Softwareentwicklung, Debugging und Architektur.",
            "persona_desc_writer" to "Kreativer Geschichtenerzähler, Redakteur und Content-Ersteller.",
            "persona_desc_researcher" to "Analysiert Daten, fasst Arbeiten zusammen und erklärt komplexe Konzepte.",
            "persona_desc_tutor" to "Erklärt Themen einfach und hilft beim Lernen und bei der Ausbildung.",
            "theme_title" to "App-Design-Thema",
            "theme_light" to "Helles Design ☀️",
            "theme_dark" to "Dunkles Design 🌙",
            "auto_notify_title" to "Statusleisten-Benachrichtigungen",
            "auto_notify_desc" to "Sendet Anfragen & Antworten mit Markdown, Formeln und Bildern automatisch in die Statusleiste.",
            "send_test_notification" to "Test-Benachrichtigung senden 🔔"
        ),
        "ru" to mapOf(
            "app_title" to "OmniChat AI",
            "chat" to "Чат",
            "providers" to "AI Провайдеры",
            "memory" to "Память",
            "mcp" to "MCP Инструменты",
            "settings" to "Настройки",
            "new_chat" to "Новый чат",
            "no_chats" to "Нет чатов. Начните новый разговор!",
            "send_hint" to "Спросите что-нибудь, прикрепите фото или файлы...",
            "active_provider" to "Активный AI",
            "web_search" to "Поиск в Web",
            "recording" to "Слушаю...",
            "voice_input" to "Голосовой ввод",
            "video_analyze" to "Извлекаю кадры и анализирую видео...",
            "autoplay_tts" to "Автоозвучка ответов (TTS)",
            "system_prompt" to "Системный промпт / Инструкции",
            "memory_desc" to "Долгосрочные факты и предпочтения о вас, сохраненные AI для контекста между чатами.",
            "add_memory" to "Добавить воспоминание",
            "category" to "Категория",
            "content" to "Содержание",
            "save" to "Сохранить",
            "delete" to "Удалить",
            "mcp_desc" to "Model Context Protocol (MCP) позволяет моделям динамически обнаруживать и запускать инструменты на клиенте.",
            "add_mcp_server" to "Добавить MCP сервер",
            "server_name" to "Имя сервера",
            "endpoint_url" to "URL Эндпоинта",
            "tools_browsing" to "Браузер инструментов",
            "tts_settings" to "Настройки озвучки текста (TTS)",
            "tts_type_local" to "Локальный системный TTS",
            "tts_type_openai" to "Кастомный OpenAI TTS эндпоинт",
            "language" to "Язык приложения",
            "edit" to "Изменить",
            "cancel" to "Отмена",
            "add_provider" to "Добавить AI провайдера",
            "provider_name" to "Название провайдера",
            "base_url" to "API Base URL",
            "api_key" to "API ключ / Токен",
            "model_name" to "Идентификатор модели",
            "priority" to "Приоритет автозамены",
            "enabled" to "Включен",
            "fallback_indicator" to "Резервный AI: Активен",
            "status_thinking" to "Обдумывание...",
            "status_searching" to "Поиск в интернете...",
            "status_generating" to "Генерация ответа...",
            "status_summarizing" to "Обобщение диалога...",
            "file_attached" to "Файл прикреплен",
            "image_attached" to "Фото добавлено",
            "video_attached" to "Видео добавлено",
            "autoplay_title" to "Автовоспроизведение TTS",
            "autoplay_on" to "Автоозвучка сообщений включена",
            "observe_media_title" to "Авто-анализ медиа из галереи/папки",
            "observe_media_desc" to "Отслеживает галерею и указанную папку. При добавлении нового фото/видео OmniChat автоматически запрашивает анализ у AI.",
            "observe_folder_label" to "Путь к отслеживаемой папке",
            "observe_prompt_label" to "Промпт для авто-анализа",
            "observe_media_folder_placeholder" to "например, /storage/emulated/0/Download",
            "search_chat" to "Поиск чатов...",
            "clear_history" to "Очистить историю",
            "clear_history_confirm" to "Вы уверены, что хотите удалить все диалоги? Это действие нельзя отменить.",
            "export_chat" to "Экспортировать чат",
            "export_json" to "Экспорт в JSON",
            "export_markdown" to "Экспорт в Markdown",
            "export_filename_prefix" to "chat_export",
            "time_now" to "Только что",
            "time_minutes" to "%d мин. назад",
            "time_hours" to "%d ч. назад",
            "time_days" to "%d дн. назад",
            "personas_title" to "Роли AI",
            "persona_default" to "Общий помощник",
            "persona_coder" to "Программист-эксперт",
            "persona_writer" to "Креативный писатель",
            "persona_researcher" to "Научный исследователь",
            "persona_tutor" to "Личный репетитор",
            "persona_desc_default" to "Полезный и лаконичный помощник на все случаи жизни.",
            "persona_desc_coder" to "Специализируется на разработке ПО, отладке и архитектуре кода.",
            "persona_desc_writer" to "Мастер историй, редактор и создатель контента.",
            "persona_desc_researcher" to "Анализирует данные, обобщает статьи и объясняет сложные темы.",
            "persona_desc_tutor" to "Доступно объясняет темы и помогает в обучении.",
            "wp_settings_title" to "Интеграция с WordPress",
            "wp_url_label" to "URL сайта (https://...)",
            "wp_user_label" to "Имя пользователя",
            "wp_app_pass_label" to "Пароль приложения",
            "wp_auto_post_label" to "Авто-постинг при экспорте",
            "wp_post_success" to "Опубликовано в WordPress!",
            "wp_post_error" to "Ошибка публикации в WordPress",
            "theme_title" to "Тема оформления",
            "theme_light" to "Светлая тема ☀️",
            "theme_dark" to "Тёмная тема 🌙",
            "auto_notify_title" to "Уведомления в статус-баре",
            "auto_notify_desc" to "Автоматическая публикация полного запроса и ответа ИИ с Markdown, формулами и изображениями прямо в статус-бар.",
            "send_test_notification" to "Отправить тестовое уведомление 🔔"
        )
    )

    fun getString(key: String, lang: String): String {
        val selectedLang = if (translations.containsKey(lang)) lang else "en"
        return translations[selectedLang]?.get(key) ?: translations["en"]?.get(key) ?: key
    }

    fun getRelativeTimeString(timestamp: Long, lang: String): String {
        val now = System.currentTimeMillis()
        val diff = now - timestamp
        
        return when {
            diff < 60_000 -> getString("time_now", lang)
            diff < 3600_000 -> {
                val minutes = (diff / 60_000).toInt()
                getString("time_minutes", lang).format(minutes)
            }
            diff < 86400_000 -> {
                val hours = (diff / 3600_000).toInt()
                getString("time_hours", lang).format(hours)
            }
            else -> {
                val days = (diff / 86400_000).toInt()
                getString("time_days", lang).format(days)
            }
        }
    }
}
