/*
 * Markdown Renderer for ESP32-P4 LVGL
 * Renders parsed markdown blocks as LVGL widgets
 */
#include "md_renderer.h"
#include "syntax_highlight.h"
#include <string.h>

// ============================================================
// Font declarations
// Custom fonts with Cyrillic + Latin Extended support
// Run generate_fonts.bat first to create these
// ============================================================

// Custom fonts with Cyrillic + Latin Extended (generated by generate_fonts.ps1).
#define USE_CUSTOM_FONTS 1
extern const lv_font_t lv_font_md_body_16;
extern const lv_font_t lv_font_md_bold_16;
extern const lv_font_t lv_font_md_italic_16;
extern const lv_font_t lv_font_md_h1_26;
extern const lv_font_t lv_font_md_h2_22;
extern const lv_font_t lv_font_md_h3_20;
extern const lv_font_t lv_font_md_code_14;

// ============================================================
// Default configuration for 720x720 display
// ============================================================

md_render_config_t md_create_default_config(void)
{
    md_render_config_t cfg = {
        // Colors
        .bg_color         = lv_color_make(0x0D, 0x11, 0x17),  // Dark background
        .text_color       = lv_color_make(0xE6, 0xED, 0xF3),  // Light text
        .code_bg_color    = lv_color_make(0x16, 0x1B, 0x22),  // Code background
        .code_text_color  = lv_color_make(0xE6, 0xED, 0xF3),  // Code text
        .code_border_color= lv_color_make(0x30, 0x36, 0x3D),  // Code border
        .h1_color         = lv_color_make(0x58, 0xA6, 0xFF),  // Blue
        .h2_color         = lv_color_make(0x7E, 0xE0, 0x8A),  // Green
        .h3_color         = lv_color_make(0xD2, 0xA8, 0xF2),  // Purple
        .link_color       = lv_color_make(0x58, 0xA6, 0xFF),  // Blue
        .quote_color      = lv_color_make(0x8B, 0x94, 0x9E),  // Gray
        .quote_border     = lv_color_make(0x58, 0xA6, 0xFF),  // Blue
        .inline_code_bg   = lv_color_make(0x26, 0x2C, 0x33),  // Dark gray
        .hr_color         = lv_color_make(0x30, 0x36, 0x3D),  // Gray
        .math_color       = lv_color_make(0xF0, 0x88, 0x3E),  // Orange
        // Syntax highlighting colors
        .syntax_keyword   = lv_color_make(0xFF, 0x7B, 0x72),  // Red
        .syntax_string    = lv_color_make(0xA5, 0xD6, 0xFF),  // Blue
        .syntax_comment   = lv_color_make(0x8B, 0x94, 0x9E),  // Gray
        .syntax_number    = lv_color_make(0x79, 0xC0, 0xFF),  // Cyan
        .syntax_preproc   = lv_color_make(0xF0, 0x88, 0x3E),  // Orange
        .syntax_type      = lv_color_make(0xFF, 0xA6, 0x57),  // Yellow
#if USE_CUSTOM_FONTS
        // Fonts with Cyrillic support
        .font_body  = &lv_font_md_body_16,
        .font_code  = &lv_font_md_code_14,
        .font_h1    = &lv_font_md_h1_26,
        .font_h2    = &lv_font_md_h2_22,
        .font_h3    = &lv_font_md_h3_20,
#else
        // Fallback: Montserrat (ASCII only, no Cyrillic)
        .font_body  = &lv_font_montserrat_16,
        .font_code  = &lv_font_montserrat_14,
        .font_h1    = &lv_font_montserrat_26,
        .font_h2    = &lv_font_montserrat_22,
        .font_h3    = &lv_font_montserrat_20,
#endif
        // Layout
        .content_width   = 672,  // 720 - 2*24 padding
    };
    return cfg;
}

// ============================================================
// Helper: create a styled label
// ============================================================

static lv_obj_t *create_label(lv_obj_t *parent, const char *text,
                               const lv_font_t *font, lv_color_t color)
{
    lv_obj_t *label = lv_label_create(parent);
    lv_label_set_text(label, text);
    lv_obj_set_style_text_font(label, font, 0);
    lv_obj_set_style_text_color(label, color, 0);
    lv_obj_set_width(label, LV_PCT(100));
    lv_label_set_long_mode(label, LV_LABEL_LONG_WRAP);
    return label;
}

// ============================================================
// Render inline text segments
// ============================================================

static void render_inline_text(lv_obj_t *parent, const md_block_t *block,
                               const md_render_config_t *cfg)
{
    if (block->inline_count == 0) {
        return;
    }

    for (int i = 0; i < block->inline_count; i++) {
        const md_inline_t *seg = &block->inline_segments[i];
        if (seg->length == 0) {
            continue;
        }

        // Create a temporary null-terminated string
        char *text = (char *)malloc(seg->length + 1);
        if (!text) {
            continue;
        }
        memcpy(text, seg->text, seg->length);
        text[seg->length] = '\0';

        lv_obj_t *label = lv_label_create(parent);

        switch (seg->type) {
        case INLINE_TEXT:
            lv_label_set_text(label, text);
            lv_obj_set_style_text_font(label, cfg->font_body, 0);
            lv_obj_set_style_text_color(label, cfg->text_color, 0);
            break;

        case INLINE_BOLD:
            lv_label_set_text(label, text);
#if USE_CUSTOM_FONTS
            lv_obj_set_style_text_font(label, &lv_font_md_bold_16, 0);
#else
            lv_obj_set_style_text_font(label, cfg->font_body, 0);
#endif
            lv_obj_set_style_text_color(label, cfg->text_color, 0);
            break;

        case INLINE_ITALIC:
            lv_label_set_text(label, text);
#if USE_CUSTOM_FONTS
            lv_obj_set_style_text_font(label, &lv_font_md_italic_16, 0);
#else
            lv_obj_set_style_text_font(label, cfg->font_body, 0);
            lv_obj_set_style_text_opa(label, LV_OPA_80, 0);
#endif
            lv_obj_set_style_text_color(label, cfg->text_color, 0);
            break;

        case INLINE_CODE:
            lv_label_set_text(label, text);
            lv_obj_set_style_text_font(label, cfg->font_code, 0);
            lv_obj_set_style_text_color(label, cfg->code_text_color, 0);
            lv_obj_set_style_bg_color(label, cfg->inline_code_bg, 0);
            lv_obj_set_style_bg_opa(label, LV_OPA_COVER, 0);
            lv_obj_set_style_pad_left(label, 4, 0);
            lv_obj_set_style_pad_right(label, 4, 0);
            lv_obj_set_style_pad_top(label, 1, 0);
            lv_obj_set_style_pad_bottom(label, 1, 0);
            lv_obj_set_style_radius(label, 3, 0);
            break;

        case INLINE_LINK:
            lv_label_set_text(label, text);
            lv_obj_set_style_text_font(label, cfg->font_body, 0);
            lv_obj_set_style_text_color(label, cfg->link_color, 0);
            lv_obj_set_style_text_decor(label, LV_TEXT_DECOR_UNDERLINE, 0);
            break;

        case INLINE_MATH:
            lv_label_set_text(label, text);
            lv_obj_set_style_text_font(label, cfg->font_code, 0);
            lv_obj_set_style_text_color(label, cfg->math_color, 0);
            lv_obj_set_style_bg_color(label, cfg->inline_code_bg, 0);
            lv_obj_set_style_bg_opa(label, LV_OPA_COVER, 0);
            lv_obj_set_style_pad_left(label, 6, 0);
            lv_obj_set_style_pad_right(label, 6, 0);
            lv_obj_set_style_radius(label, 3, 0);
            break;
        }

        lv_obj_set_width(label, LV_PCT(100));
        lv_label_set_long_mode(label, LV_LABEL_LONG_WRAP);
        free(text);
    }
}

// ============================================================
// Render code block with syntax highlighting
// ============================================================

static void render_code_block(lv_obj_t *parent, const md_block_t *block,
                               const md_render_config_t *cfg)
{
    // Code block container
    lv_obj_t *code_box = lv_obj_create(parent);
    lv_obj_set_size(code_box, cfg->content_width, LV_SIZE_CONTENT);
    lv_obj_set_style_bg_color(code_box, cfg->code_bg_color, 0);
    lv_obj_set_style_bg_opa(code_box, LV_OPA_COVER, 0);
    lv_obj_set_style_border_color(code_box, cfg->code_border_color, 0);
    lv_obj_set_style_border_width(code_box, 1, 0);
    lv_obj_set_style_radius(code_box, 6, 0);
    lv_obj_set_style_pad_all(code_box, 12, 0);
    lv_obj_set_flex_flow(code_box, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_row(code_box, 2, 0);
    lv_obj_clear_flag(code_box, LV_OBJ_FLAG_SCROLLABLE);

    // Syntax colors array: [keyword, string, comment, number, preproc, type, plain]
    lv_color_t colors[7] = {
        cfg->syntax_keyword, cfg->syntax_string, cfg->syntax_comment,
        cfg->syntax_number, cfg->syntax_preproc, cfg->syntax_type,
        cfg->text_color
    };

    // Tokenize and render each line
    const char *text = block->text;
    uint16_t remaining = block->length;

    while (remaining > 0) {
        // Find end of line
        const char *line_end = memchr(text, '\n', remaining);
        uint16_t line_len;
        if (line_end) {
            line_len = line_end - text;
        } else {
            line_len = remaining;
        }

        // Skip \r
        if (line_len > 0 && text[line_len - 1] == '\r') {
            line_len--;
        }

        // Tokenize the line
        code_token_t tokens[MAX_TOKENS];
        int token_count = syntax_tokenize(text, line_len, tokens);

        // Create a flex row for this line
        lv_obj_t *line_row = lv_obj_create(code_box);
        lv_obj_set_size(line_row, LV_PCT(100), LV_SIZE_CONTENT);
        lv_obj_set_style_bg_opa(line_row, LV_OPA_TRANSP, 0);
        lv_obj_set_style_border_width(line_row, 0, 0);
        lv_obj_set_style_pad_all(line_row, 0, 0);
        lv_obj_set_flex_flow(line_row, LV_FLEX_FLOW_ROW);
        lv_obj_set_flex_align(line_row, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                               LV_FLEX_ALIGN_START);
        lv_obj_clear_flag(line_row, LV_OBJ_FLAG_SCROLLABLE);

        // Render each token
        for (int t = 0; t < token_count; t++) {
            char *token_text = (char *)malloc(tokens[t].length + 1);
            if (!token_text) {
                continue;
            }
            memcpy(token_text, tokens[t].start, tokens[t].length);
            token_text[tokens[t].length] = '\0';

            lv_obj_t *token_label = lv_label_create(line_row);
            lv_label_set_text(token_label, token_text);
            lv_obj_set_style_text_font(token_label, cfg->font_code, 0);
            lv_color_t tok_color = syntax_get_color(tokens[t].type, colors);
            lv_obj_set_style_text_color(token_label, tok_color, 0);
            lv_obj_set_style_bg_opa(token_label, LV_OPA_TRANSP, 0);

            free(token_text);
        }

        // Move to next line
        if (line_end) {
            text = line_end + 1;
            remaining -= (line_len + 1);
        } else {
            break;
        }
    }
}

// ============================================================
// Render individual block types
// ============================================================

static void render_header(lv_obj_t *parent, const md_block_t *block,
                          const md_render_config_t *cfg)
{
    const lv_font_t *font;
    lv_color_t color;

    switch (block->header_level) {
    case 1:
        font = cfg->font_h1;
        color = cfg->h1_color;
        break;
    case 2:
        font = cfg->font_h2;
        color = cfg->h2_color;
        break;
    default:
        font = cfg->font_h3;
        color = cfg->h3_color;
        break;
    }

    lv_obj_t *label = create_label(parent, block->text, font, color);
    lv_obj_set_style_pad_top(label, 16, 0);
    lv_obj_set_style_pad_bottom(label, 8, 0);
}

static void render_paragraph(lv_obj_t *parent, const md_block_t *block,
                             const md_render_config_t *cfg)
{
    if (block->inline_count > 0) {
        lv_obj_t *para = lv_obj_create(parent);
        lv_obj_set_size(para, cfg->content_width, LV_SIZE_CONTENT);
        lv_obj_set_style_bg_opa(para, LV_OPA_TRANSP, 0);
        lv_obj_set_style_border_width(para, 0, 0);
        lv_obj_set_style_pad_all(para, 0, 0);
        lv_obj_set_flex_flow(para, LV_FLEX_FLOW_COLUMN);
        lv_obj_clear_flag(para, LV_OBJ_FLAG_SCROLLABLE);

        render_inline_text(para, block, cfg);
    } else if (block->text) {
        create_label(parent, block->text, cfg->font_body, cfg->text_color);
    }
}

static void render_blockquote(lv_obj_t *parent, const md_block_t *block,
                              const md_render_config_t *cfg)
{
    lv_obj_t *quote_box = lv_obj_create(parent);
    lv_obj_set_size(quote_box, cfg->content_width, LV_SIZE_CONTENT);
    lv_obj_set_style_bg_opa(quote_box, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(quote_box, 2, 0);
    lv_obj_set_style_border_color(quote_box, cfg->quote_border, 0);
    lv_obj_set_style_border_side(quote_box, LV_BORDER_SIDE_LEFT, 0);
    lv_obj_set_style_pad_left(quote_box, 12, 0);
    lv_obj_set_flex_flow(quote_box, LV_FLEX_FLOW_COLUMN);
    lv_obj_clear_flag(quote_box, LV_OBJ_FLAG_SCROLLABLE);

    if (block->inline_count > 0) {
        render_inline_text(quote_box, block, cfg);
    } else if (block->text) {
        create_label(quote_box, block->text, cfg->font_body, cfg->quote_color);
    }
}

static void render_list_item(lv_obj_t *parent, const md_block_t *block,
                             const md_render_config_t *cfg)
{
    lv_obj_t *row = lv_obj_create(parent);
    lv_obj_set_size(row, cfg->content_width, LV_SIZE_CONTENT);
    lv_obj_set_style_bg_opa(row, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(row, 0, 0);
    lv_obj_set_style_pad_all(row, 0, 0);
    lv_obj_set_flex_flow(row, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(row, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START,
                           LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(row, LV_OBJ_FLAG_SCROLLABLE);

    /* Bullet / number */
    const char *marker;
    if (block->type == MD_BLOCK_LIST_UL) {
        marker = "\u2022 ";  // Bullet
    } else {
        /* Extract the original number from block text position is not available,
         * so we use a simple counter approach: render with "1. " as fallback. */
        marker = "1. ";  // TODO: extract actual number from source
    }

    lv_obj_t *marker_label = lv_label_create(row);
    lv_label_set_text(marker_label, marker);
    lv_obj_set_style_text_font(marker_label, cfg->font_body, 0);
    lv_obj_set_style_text_color(marker_label, cfg->h1_color, 0);

    // Content
    if (block->inline_count > 0) {
        lv_obj_t *content = lv_obj_create(row);
        lv_obj_set_size(content, cfg->content_width - 30, LV_SIZE_CONTENT);
        lv_obj_set_style_bg_opa(content, LV_OPA_TRANSP, 0);
        lv_obj_set_style_border_width(content, 0, 0);
        lv_obj_set_style_pad_all(content, 0, 0);
        lv_obj_set_flex_flow(content, LV_FLEX_FLOW_COLUMN);
        lv_obj_clear_flag(content, LV_OBJ_FLAG_SCROLLABLE);
        render_inline_text(content, block, cfg);
    } else if (block->text) {
        create_label(row, block->text, cfg->font_body, cfg->text_color);
    }
}

static void render_hr(lv_obj_t *parent, const md_render_config_t *cfg)
{
    lv_obj_t *line = lv_obj_create(parent);
    lv_obj_set_size(line, cfg->content_width, 2);
    lv_obj_set_style_bg_color(line, cfg->hr_color, 0);
    lv_obj_set_style_bg_opa(line, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(line, 0, 0);
    lv_obj_set_style_radius(line, 1, 0);
    lv_obj_set_style_pad_top(line, 12, 0);
    lv_obj_set_style_pad_bottom(line, 12, 0);
}

// ============================================================
// Public API
// ============================================================

void md_render_block(lv_obj_t *parent, const md_block_t *block,
                     const md_render_config_t *cfg)
{
    switch (block->type) {
    case MD_BLOCK_HEADER:
        render_header(parent, block, cfg);
        break;
    case MD_BLOCK_PARAGRAPH:
        render_paragraph(parent, block, cfg);
        break;
    case MD_BLOCK_CODE:
        render_code_block(parent, block, cfg);
        break;
    case MD_BLOCK_LIST_UL:
    case MD_BLOCK_LIST_OL:
        render_list_item(parent, block, cfg);
        break;
    case MD_BLOCK_QUOTE:
        render_blockquote(parent, block, cfg);
        break;
    case MD_BLOCK_HR:
        render_hr(parent, cfg);
        break;
    case MD_BLOCK_EMPTY:
        break;
    }
}

void md_render_document(const md_document_t *doc, lv_obj_t *parent,
                        const md_render_config_t *cfg)
{
    if (!doc || !parent) {
        return;
    }

    // Set background
    lv_obj_set_style_bg_color(parent, cfg->bg_color, 0);
    lv_obj_set_style_bg_opa(parent, LV_OPA_COVER, 0);

    // Create scrollable content container
    lv_obj_t *content = lv_obj_create(parent);
    lv_obj_set_width(content, cfg->content_width);
    lv_obj_set_height(content, LV_SIZE_CONTENT);
    lv_obj_center(content);
    lv_obj_set_style_bg_opa(content, LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(content, 0, 0);
    lv_obj_set_style_pad_all(content, 24, 0);
    lv_obj_set_flex_flow(content, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_style_pad_row(content, 4, 0);
    lv_obj_set_scroll_dir(content, LV_DIR_VER);
    lv_obj_set_scrollbar_mode(content, LV_SCROLLBAR_MODE_AUTO);

    // Render each block
    for (int i = 0; i < doc->count; i++) {
        md_render_block(content, &doc->blocks[i], cfg);
    }
}
